"""initial schema

Revision ID: 717c2541940c
Revises: 
Create Date: 2026-05-10 18:03:58.766168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717c2541940c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STANDARD', name='userrolechoice'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('cover_path', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_tag_per_user')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_user_tag', ['user_id', 'name'], unique=False)

    op.create_table('book_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', 'user_id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('last_read', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'IN_PROGRESS', 'FINISHED', name='bookprogresschoice'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='unique_user_book_bookmark')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('idx_user_book', ['user_id', 'book_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('idx_user_book')

    op.drop_table('bookmarks')
    op.drop_table('book_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_user_tag')

    op.drop_table('tags')
    op.drop_table('books')
    op.drop_table('users')
    # ### end Alembic commands ###
